export class Adjective {
    public rank: string;
    public word: string;
    public fNom: string;
    public fGen: string;
    public fDat: string;
    public fAcc: string;
    public fInst: string;
    public fPrep: string;
    public nNom: string;
    public nGen: string;
    public nDat: string;
    public nAcc: string;
    public nInst: string;
    public nPrep: string;
    public mNom: string;
    public mGen: string;
    public mDat: string;
    public mAcc: string;
    public mInst: string;
    public mPrep: string;
    public plNom: string;
    public plGen: string;
    public plDat: string;
    public plAcc: string;
    public plInst: string;
    public plPrep: string;
    public en: string;
}
